name = "RigidBodyTreeInspector"
uuid = "82daab19-8fc9-5c1e-9f69-37d6aaa0269b"
version = "0.6.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DrakeVisualizer = "49c7015b-b8db-5bc5-841b-fcb31c578176"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
InteractBase = "d3863d7c-f0c8-5437-a7b4-3ae773c01009"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopThrottle = "39f5be34-8529-5463-bac7-bf6867c840a3"
MechanismGeometries = "931e9471-e8fb-5385-a477-07ad12718aca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ColorTypes = "0.8"
CoordinateTransformations = "0.5"
DrakeVisualizer = "0.4"
GeometryTypes = "0.7"
Interact = "0.8, 0.9, 0.10"
InteractBase = "0.7, 0.8, 0.9, 0.10"
Interpolations = "0.9, 0.10, 0.11, 0.12"
LoopThrottle = "0.1"
MechanismGeometries = "0.3"
NBInclude = "2"
RigidBodyDynamics = "2"
Rotations = "0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11"
StaticArrays = "0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11"
ValkyrieRobot = "0.2"
julia = "1"

[extras]
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ValkyrieRobot = "c74b26e8-f247-5d24-b013-c11a2bbd97c6"

[targets]
test = ["Interact", "NBInclude", "Test", "Random", "ValkyrieRobot"]
